apiVersion: v1
kind: Namespace
metadata:
  name: namespace-gitops
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespace-app
  namespace: namespace-gitops
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/cdelashmutt-pivotal/gbs-gitops
      ref: origin/main
      subPath: config

  template:
  - ytt: {}

  deploy:
  - kapp: {}